### PR TITLE
Remove SealedBite: repository doesn't exist anymore

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Calinou** [comment]
@securas Out of curiosity, why was the repository removed or made private? Could it be made public again if possible?

**Comment by securas** [comment]
I took it out for 3 reasons. 1. It was meant to be a teaching tool. But I kept having folks trying to sell versions of it, malwared versions of it and even got some harrassement from folks that wanted the rights to the assets released as well, which I don’t own entirely. 2. It was made in a very old version of Godot. So objective 1 was no longer possible, in practice. And finally, 3. after so many years, I decided to turn it in a commercial game: https://store.steampowered.com/app/2849650/Sealed_Bite_Extended/I hope you can understand that, although this may change in the future, I currently have only incentives to keep it closed source.On Oct 6, 2024, at 0:32, Hugo Locurcio ***@***.***> wrote:﻿
@securas Out of curiosity, why was the repository removed or made private? Could it be made public again if possible?

**Comment by Calinou** [comment]
@dustdfg Can you rebase this PR to fix merge conflicts?

**Comment by ghost** [comment]
@Calinou done

**Comment by Calinou** [comment]
Merged manually as part of https://github.com/godotengine/awesome-godot/pull/349. Thanks for the contribution nonetheless!

**Pull request closed without merging**
