### PR TITLE
Add LimboAI plugin (C++ module/extension)

### PR DESCRIPTION
**Pull request by limbonaut**
This PR adds LimboAI to the list of plugins.

Hi! I'm the author of this plugin, and I've been working on it for a while now. Half a year ago, I decided to open-source it. It has gathered a small community around it, and I think it's awesome! 😊

LimboAI is an open-source C++ plugin for Godot Engine 4 providing a combination of **Behavior Trees** and **State Machines**, which can be used together to create complex AI behaviors. It comes with a behavior tree editor, built-in documentation, visual debugger, and more! While it is implemented in C++, it fully supports GDScript for [creating your own tasks](https://limboai.readthedocs.io/en/latest/getting-started/custom-tasks.html) and states.

https://github.com/limbonaut/limboai

You should check out our awesome demo project. Here's a demonstration:

https://github.com/godotengine/awesome-godot/assets/2766569/9e940f16-1e96-4726-9e13-aa4877025063

### CODE REVIEW

**Comment by limbonaut** [comment]
Since it can be compiled as a module or a GDExtension library, I was not sure where to put it, so I placed it in plugins.

**Review by Calinou — APPROVED** [review]
Thanks! Congratulations for your first merged pull request :tada:

**Comment by Calinou** [comment]
> Since it can be compiled as a module or a GDExtension library, I was not sure where to put it, so I placed it in plugins.

I agree with placing it in the Plugins section if it can run either as a module or GDExtension.

**Comment by limbonaut** [comment]
Thanks! :smiley:

**Pull request merged**
