### PR TITLE
Add clipboard narrator to non-game projects

### LINKED ISSUE #268: Submitting a project for Godot 4 possible yet?
Hello I want to submit an open source tool I made in Godot but it's made for Godot 4 only. Is it possible to add a new Godot 4 tab or are they not being accepted yet?

Edit: nvm I saw a 4.0 module listed.

### PR DESCRIPTION
**Pull request by lesleyrs**
Closes https://github.com/godotengine/awesome-godot/issues/268

Created new section for 4.0 tools/utilities and added my tool to it.

### CODE REVIEW

**Comment by lesleyrs** [comment]
It seems that Linux has a problem with loading the voice, it doesn't work as expected with number keys and otherwise when it works it takes like 5 seconds or so. (Godot 4 rc 2).

I've been heavily using this on Windows 10 and almost everything just works. I'm unsure what causes Linux to be slow but it also applies to the official tts_demo. But yea test it on Windows to see how it works.

1 key difference is that the way it loads voices on Windows it should only find the English one as other languages are stored elsewhere (in my experience). While on Linux it loads all the voices. I'm not looping through them after they are loaded though so idk.

Removed an extra whitespace from the other project that was conflicting btw.

**Comment by Calinou** [comment]
cc @nightblade9

**Comment by nightblade9** [comment]
Not sure why I'm CCed, but thanks?

- Good to know about the number key thing, I'll add that to my list of things to test
- The five-second delay could be loading up all the voices. In my limited experience, you load voices once (ever) and store the data/ID of the one you want to reuse.
- You definitely need to loop/search through voices and pick one. I use the first voice as a fallback if I can't find the one I want.

**Comment by lesleyrs** [comment]
> * Good to know about the number key thing, I'll add that to my list of things to test

No number keys is what I use for interrupting a voice, specific to my application here. Seems broken on Linux.

> * The five-second delay could be loading up all the voices. In my limited experience, you load voices once (ever) and store the data/ID of the one you want to reuse.
> * You definitely need to loop/search through voices and pick one. I use the first voice as a fallback if I can't find the one I want.

I only loop when the application loads + when you search just like the original demo, but the delay happens *everytime* you try to start/interrupt a voice. This does not happen on Windows but it also doesn't have that many voices.

I don't think anyone is tracking the problem but I also don't have data from other people about this. So i'm unsure if the problem is just on my end.

@nightblade9 have you not noticed any delay like this when a LOT of voices are loaded on Linux?

**Comment by nightblade9** [comment]
> @nightblade9 have you not noticed any delay like this when a LOT of voices are loaded on Linux?

No, I haven't noticed.

My Arch-based system reports 13362 (13k) voices. Any time I invoke `tts_say` or `tts_stop`, it takes about a second before it stops and then speaks the intended message.

**Comment by nightblade9** [comment]
It looks like this issue is Linux-specific, and - I'm tempted to say - not Godot specific, since Godot just warps and uses the underlying system library.

On Windows, using `tts_stop()` and then `tts_speak` immediately stops and speaks the new message. This is expected. On Linux, there's a ~1 second delay. This is bad.

Personally, I am not really interested in Linux TTS, since every blind person I asked said they use Windows with NVDA and that Linux/Orca is very niche. I'm okay with the Windows performance for players, and Linux performance for development. Ideally, this should be fixed (maybe we need a new issue for this?)

**Comment by lesleyrs** [comment]
> It looks like this issue is Linux-specific, and - I'm tempted to say - not Godot specific, since Godot just warps and uses the underlying system library.
> 
> On Windows, using `tts_stop()` and then `tts_speak` immediately stops and speaks the new message. This is expected. On Linux, there's a ~1 second delay. This is bad.
> 
> Personally, I am not really interested in Linux TTS, since every blind person I asked said they use Windows with NVDA and that Linux/Orca is very niche. I'm okay with the Windows performance for players, and Linux performance for development. Ideally, this should be fixed (maybe we need a new issue for this?)

Same for me, I think this should be mentioned in the docs first of all. But it'd be good to get more reports about this before doing so for clarity. 1 second delay is acceptable but on my 2012 laptop it gets kind of unusable even though the application itself is running fine otherwise.

**Comment by nightblade9** [comment]
> I think this should be mentioned in the docs first of all

I hesitate to include anything like this in the docs; first, because it depends on your system specs. And second, because I can't be sure that anything that works on one Linux distro, works on another Linux distro.

Ultimately, Godot just wraps and uses the system libraries for text-to-speech. Many of these issues could be upstream issues from those underlying system libraries. I don't know if there's a process to verify and report these issues upstream; that would be ideal.

**Comment by Calinou** [comment]
The documentation should definitely mention that *some* delay is expected when using `tts_start()` and `tts_stop()`, as this can have various implications.

**Comment by nightblade9** [comment]
> The documentation should definitely mention that _some_ delay is expected when using `tts_start()` and `tts_stop()`, as this can have various implications.

I'll add this to my documentation page PR, this looks like the wrong repo (awesome-godot).

**Comment by lesleyrs** [comment]
@Calinou Can we complete this PR or is there a problem? It should be working on linux by now with the correct libraries installed, but I've not used it much outside of windows. Understandable if busy though.

**Review by Calinou — APPROVED** [review]
Thanks! Congratulations for your first merged pull request :tada:

**Pull request merged**
