### PR TITLE
Added ic3bug's Multiplayer shooter projects

### PR DESCRIPTION
**Pull request by asvvvad1**

### CODE REVIEW

**Comment by Calinou** [comment]
Thanks!

**Comment by asvvvad1** [comment]
> Thanks!

My first accepted pull request ^^

**Comment by catpreneur** [comment]
Those repositories are 404'd

**Comment by Calinou** [comment]
@oofdog It seems the user @ic3bug has disappeared entirely from GitHub for some reason. I can see two mirrors [here](https://github.com/blockspacer/Godot-3.2-Multiplayer-FPS) and [here](https://github.com/jasonswearingen/TPS-MP), so I guess I'll link to those for now.

**Pull request merged**
