### PR TITLE
Sort entries by Godot version, clarify open source status

### PR DESCRIPTION
**Pull request by ghost**
Sorts games, projects, templates, demos, tutorials, modules, plugins and scripts according to Godot version.  

Screenshot (36)

### CODE REVIEW

**Review by Calinou — CHANGES_REQUESTED** [review]
Nice work :slightly_smiling_face: 

Now that projects are sorted by version, you should also remove the Godot version indicators between parentheses like `(Godot 3.2)`.

**Comment by ghost** [comment]
Hello @Calinou I have removed the Godot version indicators between parentheses like `(Godot 3.2)`.
For projects that use mono there is now only `(Mono)` and for projects that require a module there is now `(needs custom engine modules)`.

PS: I did not delete the Godot version indicators in the various Godot version sections.

**Comment by Calinou** [comment]
Should be good to merge after replacing all 4 instances of "Various Godot version" with "Various Godot version**s**".

**Comment by ghost** [comment]
@Calinou  Done

**Review by Calinou — APPROVED** [review]
Thanks a lot for carrying out this work!

**Comment by Xrayez** [comment]
What if a particular plugin/project is intended to target all future Godot versions by design, but only currently implemented for a single version of the engine, what category it belongs to?

**Comment by Calinou** [comment]
> What if a particular plugin/project is intended to target all future Godot versions by design, but only currently implemented for a single version of the engine, what category it belongs to?

I'd say Godot 3.2 (then 3.3 once 3.3 is released).

**Pull request merged**
